FROM ubuntu
RUN apt-get update
RUN apt-get install vim -y
RUN apt-get install valgrind -y
RUN apt-get install gcc -y
RUN apt-get install python3 -y
RUN apt-get install python3-pip idle3 -y && \
    pip3 install --no-cache-dir --upgrade pip
